version: "3.9"
services:
  fields-multiverse-core:
    container_name: fields-multiverse
    build: .
    image: myfields-multiverse:latest
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      FIELDS_MULTIVERSE_DATABASE_CLIENT: ${FIELDS_MULTIVERSE_DATABASE_CLIENT}
      FIELDS_MULTIVERSE_DATABASE_HOST: fields-multiverse-db
      FIELDS_MULTIVERSE_DATABASE_NAME: ${FIELDS_MULTIVERSE_DATABASE_NAME}
      FIELDS_MULTIVERSE_DATABASE_USERNAME: ${FIELDS_MULTIVERSE_DATABASE_USERNAME}
      FIELDS_MULTIVERSE_DATABASE_PASSWORD: ${FIELDS_MULTIVERSE_DATABASE_PASSWORD}
      FIELDS_MULTIVERSE_DATABASE_PORT: ${FIELDS_MULTIVERSE_DATABASE_PORT}
      FIELDS_MULTIVERSE_DATABASE_SSL: ${FIELDS_MULTIVERSE_DATABASE_SSL}
      FIELDS_MULTIVERSE_JWT_SECRET: ${FIELDS_MULTIVERSE_JWT_SECRET}
      FIELDS_MULTIVERSE_API_TOKEN_SALT: ${FIELDS_MULTIVERSE_API_TOKEN_SALT}
      FIELDS_MULTIVERSE_PORT: ${FIELDS_MULTIVERSE_PORT}
      FIELDS_MULTIVERSE_APP_KEYS: ${FIELDS_MULTIVERSE_APP_KEYS}
    ports:
      - "${FIELDS_MULTIVERSE_PORT}:1337"
    # volumes:
    #  - ./:/opt/app  
    networks:
      - fields-multiverse-network
    depends_on:
      fields-multiverse-db:
        condition: service_healthy

  fields-multiverse-db: 
    image: mysql:5.7.17
    command: --default-authentication-plugin=mysql_native_password
    container_name: fields-multiverse-db
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${FIELDS_MULTIVERSE_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${FIELDS_MULTIVERSE_DATABASE_NAME}
      MYSQL_USER: ${FIELDS_MULTIVERSE_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${FIELDS_MULTIVERSE_DATABASE_PASSWORD}
    ports:
      - '${FIELDS_MULTIVERSE_DATABASE_PORT}:3306'
    healthcheck:
        test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
        timeout: 20s
        retries: 10      
    networks:
      - fields-multiverse-network

networks:
  fields-multiverse-network:
    driver: bridge
