version: "3"
services:
  fields-multiverse-core:
    container_name: fields-multiverse
    build: .
    image: myfields-multiverse:latest
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: fields-multiverse-db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SSL: ${DATABASE_SSL}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
    ports:
      - "${PORT}:1337"
    volumes:
      - ./:/opt/app  
    networks:
      - fields-multiverse-network
    depends_on:
      - fields-multiverse-db

  fields-multiverse-db: 
    image: mysql:5.7.17
    command: --default-authentication-plugin=mysql_native_password
    container_name: fields-multiverse-db
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:3306'
    networks:
      - fields-multiverse-network

networks:
  fields-multiverse-network:
    driver: bridge